### ISSUE TITLE
Structure review

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-rest-cdi#11]
It looks pretty good (I can't judge the technical coverage but as far as the technology is there I think the guide describes it pretty well). I like the explanations in general - they seem to have the right level of detail. And the length of the guide is much better.

Following on from what we talked about yesterday regarding creating/updating files, yes, I think you need to do the same here with creating the classes then describing them. So have them create the class file (see the intro REST guide for the style) and then explain the relevant bits of the class (or specifically a bean in this case). Where you have the two beans in the scopes section, get them to create the first bean, then describe the relevant bits of it, then ask them to create the second bean and do the same. Start each explanation giving a brief overview of what the point of that particular bean is.

I think I understand why you’ve done it the way you have - because you’re trying to explain scopes and contexts separately from dependency injection? I think you're right to separate the discussion of each (collapsing them together would be messy and confusing) but I think you can just refer back to the code of the bean when you talk about the `@Inject` annotation in the next section. And, so that someone reading the first section isn't left wondering "but what about that @Inject annotation that hasn't been explained, what's that for?", I think you can just flag up that that will be described in the next section.

So, you could add a sentence at the end of the ‘managing scopes and contexts’ section saying something like “The InventoryManager bean also contains another annotation, `@Inject`, which will be explained in the next section.” (there might be a better way to say that). Then straight after the ‘Injecting a dependency’ heading, add something like “The InventoryResource bean depends on the InventoryResource bean. Instead of doing xxxx (the thing you’d do without the @Inject annotation), the InventoryManager bean uses the @Inject annotation to automatically call that dependency (or whatever the correct terminology is). Take a look at the @Inject line in the InventoryManager bean code….” Something like that? Give it a try and we can see how it looks/reads.

I also made a note of some style things as I went (though I didn't do a full review for that) and you'll probably get them again from ID review but I've included them here in case you want to fix them first (or talk to the ID person about how to fix them if you're not sure):

* Is the phrase “well-defined contexts” understandable in “You will use scopes to bound objects in this application to their well defined-contexts.”? (maybe, I don’t know)
* Don’t capitalise Contexts etc. They're just words, not names.
* Reduce the amount of future tense (eg only do that in the What you’ll learn section and say “you will work with” instead of  “you will be working with” to avoid clunkiness; don't use future tense when describing how the app works; don't use it in sections further down the guide)
* When you mention ‘one function’ and ’the second function’, give the name of the function so its easy to see in the code. Ah, or is (get) and (list) for that purpose? I think they just need highlighting properly (with backticks).
* Remove “Note that….” (“Note that while this bean can also be application-scoped, request scope is short-lived and is therefore ideal for HTTP requests.”) - it’s redundant words. Just explain that while the bean can be app-scoped, it is more appropriate to use the request scope etc.
* I’m not sure about “we’re giving you ”. “You can find a client….”?
* Shorten “This class is responsible for communicating…” to “This class communicates with…”
* Javadocs mentions could do with a link to where to find those javadocs.

Thanks for doing this - it's looking good.

**Comment by evelinec** [comment]
All of the points suggested had been incorporated.

**Comment by evelinec** [comment]
To be fixed in #21.
