### ISSUE TITLE
User Review

### ISSUE THREAD

**Issue by gkertaseferi** [OpenLiberty/draft-guide-rest-cdi#14]
It looks good to me. The steps are clear. 

- [x] The start/pom.xml in line 9 `<artifactId>io.openliberty.guides.rest-cdi</artifactId>` needs to be changed to look like the finish/pom.xml  `<artifactId>io.openliberty.guides.cdi-intro</artifactId>`.

**Comment by gkertaseferi** [comment]
1. Also, it might be a good idea to wrap the lines to be shorter.
2. ```git clone https://github.com/openliberty/guide-cdi-intro.git 
    cd guide-cdi-intro/start```
    -->
  ```git clone https://github.com/OpenLiberty/draft-guide-rest-cdi.git
    draft-guide-rest-cdi/start```

**Comment by evelinec** [comment]
We're wrapping lines at 100 characters.

**Comment by evelinec** [comment]
The gitclone common adoc file was to be updated to reflect the draft guide as well.
