### ISSUE TITLE
SystemClient should have a constructor

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/draft-guide-rest-cdi#15]
The `init` methods in the SystemClient class are behaving like constructors and hence should be replaced by constructors. This is what the SystemClient class should look like:

```
  public SystemClient(String hostname) {
      this.init(hostname, DEFAULT_PORT);
  }
  
  public SystemClient(String hostname, int port) {
      this.init(hostname, port);
  }

  // Helper method to set the attributes.
  private void init(String hostname, int port) {
    this.url = buildUrl(PROTOCOL, hostname, port, SYSTEM_PROPERTIES);
    this.clientBuilder = buildClientBuilder(this.url);
  }
```

Then the SystemClient can be initialized whenever its needed (inside methods not as a instance variable) like so:

```
SystemClient systemClient = new SystemClient(hostname, 9080);
```

**Comment by evelinec** [comment]
Assign to @JunyiSun as she worked on this originally. This is a priority two item for you. Thanks.

**Comment by JunyiSun** [comment]
@Kubik42 It was designed to do so. In the InventoryManager.java file, the SystemClient has to be instantiated as a class attribute (outside of any methods), so its constructor cannot have any parameters. The init() will set its hostname as one of the parameters within the getProperties() method after the SystemClient instance has been created.

**Comment by Kubik42** [comment]
I looked it over again and I see why you guys decided to do that. SystemClient is sort of like a client object, and re-instantiating it every time its needed seems redundant. However, are there any cases where you need to instantiate it more than once? I think this would only occur when there are 2+ system services on different hosts. In that case, it makes sense to instantiate it 2+ times because each client is essentially different and connects to a different host.
