### ISSUE TITLE
Spelling mistake in "Try what you’ll build" section

### ISSUE THREAD

**Issue by GraceJansen** [OpenLiberty/draft-guide-rest-cdi#17]
"This is the staring point of the inventory service and it displays the current contents of the inventory"

Should this not say **starting** instead of staring?

**Comment by GraceJansen** [comment]
I have edited the README.adoc on GitHub and so this should have been resolved but @evelinec please can you confim this.

**Comment by evelinec** [comment]
@GraceJansen I didn't see any changes on github. I fixed it through my branch. Thanks.
