### ISSUE TITLE
EndpointTest cleanup

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/draft-guide-rest-cdi#19]
- [x] Should rename `INVENTORY_HOSTS` to `INVENTORY_SYSTEMS` to better reflect the actual value stored in the variable.

- [x] Extra print statement on line 99

**Comment by JunyiSun** [comment]
extra print statement:
System.out.println(obj.getJsonArray("systems").getJsonObject(0)
                          .get("hostname").toString());

**Comment by evelinec** [comment]
@gkertaseferi can you help doing the clean up for this test class? Have the issuer to code review the changes; after approval, the changes need to be made into all of the other guides running the Endpoint Test as well. Thanks.

**Comment by gkertaseferi** [comment]
@evelinec I don't think I have time to do this. I'm sorry.

**Comment by evelinec** [comment]
To be fixed in #21.
