### ISSUE TITLE
SystemClient exception handling

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/draft-guide-rest-cdi#20]
I don't think `buildUrl()` and `buildClientBuilder()` handle exceptions well. They just print two exception names when **any** Exception is caught. These print statements should have some meaningful text in them and should be unique to each exception.

For example, exception handling in `getPropertiesHelper()` is done much better, with error messages for different types of exceptions.

**Comment by evelinec** [comment]
@JunyiSun when you have a chance, can you take a look at this issue? Thanks.

**Comment by JunyiSun** [comment]
Fixed by #35
