### ISSUE TITLE
Some guides-common links already have titles -> Remove duplicates

### ISSUE THREAD

**Issue by Ahmad-Ayyoub** [OpenLiberty/draft-guide-rest-cdi#24]
For example, https://github.com/OpenLiberty/guides-common/blob/master/gitclone.adoc has 

== Getting started title 

The title should not be shown otherwise this will cause a duplicate of titles. Please make sure you remove any title that you reference from guide-common links

mention others if they have the same thing

**Comment by evelinec** [comment]
Fixed #25

**Comment by evelinec** [comment]
Fixed for CDI guide. Let's remind the team of this, and open issue for their repo if there's a problem.
