### ISSUE TITLE
review

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/draft-guide-rest-cdi#3]
**What you’ll Learn**
- "Learn" shouldn't be capitalized
=> fixed. It was inherited from the previous version
- your language is a bit quirky in the section, sentences dont really flow that well. For example, the majority of the inventory application is built in this guide so why are you saying "This guide will complete building this application using CDI services."? It would also sound much better if it instead said something like "You will add CDI to this application to complete it".
=> not relevant anymore as building the inv app part of the guide is removed to shift focus on using cdi only. 
- you should also explain what the application does first rather than saying right away thats its made up of two services
=> changed accordingly.
- All in all, I dont think this section needed to be changed at all. It already had CDI focus. 
=> same as point 2 above. 

**Try what you’ll build**
- the future tense you added here is not necessary
=> I think present tense is ok too. 
- also, I believe only local machines work. Say the team in UK, we won't be able to access their system properties even if they run the system service.
=> I believe as long as the network allows, the system service can run anywhere. I'll double check with team to make sure. 

**Creating the inventory management application**
- I'd rather keep the old section here. There is too many issues with this section now. The whole point of this section was to roughly outline what the user is building, yet you're already saying "inventory manager bean" and "inventory resource". The users are not familiar with these terms yet.  Originally, I wanted to explain it at a very high level so its easy for anyone to understand. 
=> not relevant anymore as building the inv app part of the guide is removed to shift focus on using cdi only. 
- this sentence "CDI scopes and contexts are used in this component to handle the interactions in order to establish a loosely coupled infrastructure." makes no sense. Handle what interactions? What do you mean by loosely coupled infrastructure? See this is the main problem, its too low level. We don't want to go into detail here. The details come later when these classes are actually built.
=> fixed

**Creating the inventory manager bean**
- "an `InventoryUtil` class and the `JsonMessages` enum` class" is incorrect, you don't say "an class", you say "a class" and "an enum", it should be the way it was.
=> didn't think this sentence was changed from previous version of the guide. but it's revised in the latest version already. 

**Injecting dependency into the inventory resource**
- i don't like the title of this section. The users haven't yet written the inventory resource. Perhaps it should isntead be "Creating the inventory resource and injecting dependencies"
=> again, not relevant anymore as building the inv app part of the guide is removed to shift focus on using cdi only. 

**Testing the inventory application**
- "There are a few test case methods to test the functionality of your inventory application." -> "Let's break down the test cases:"
=> good suggestion, changed. 
- remove "the" and "method" from test case bullet points. Example: "testEmptyInventory() verifies that the inventory is initially empty when the server first starts up."
=> fixed
- "There are some helper methods that are used throughout the tests. " -> "Finally, notice that you're using a few helper method throughout the tests. You can find complete javadocs for these under the finish directory for reference..."
=> fixed

All in all I don't like the direction you turned this guide (ie. completing a restful web service). This service wouldn't work without CDI, so the user's aren't really completing it, they are fixing it. The guide is also very awkward now, the Application class is provided but everything else is to be written? Then the users are really writing the whole app not just adding cdi into it. I really think its best for them to build everything from scratch the way it was. This way they understand the app better. Especially considering that many of the future guides will build on top.

**Comment by evelinec** [comment]
Close this issue. Pls review the revised guide when you have a chance. Thank you.
