### ISSUE TITLE
"Bound" should be "bind"?

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-rest-cdi#36]
- [x] "You will use scopes to bound objects in this application".
"Bound" should be "bind" here?

- [x] Remind the users where they should run the mvn commands

**Comment by evelinec** [comment]
I don't really like adding a lot of "cd" in the command, seems too obvious.

**Comment by yeekangc** [comment]
It is not.  Users have encountered problems.  At least, reminders to where they should run the commands.

**Comment by evelinec** [comment]
Fixed.
