### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/draft-guide-rest-cdi#6]
- [x] You need to uncomment common includes (ex. Getting started, Building and running the application, Running the tests, etc.). I didn't add these for the sake of presenting a fully generated html during our prototyping meetings.

**What you'll learn**
- [x] "You will learn how to use CDI in a simple inventory management application to manage scopes and inject dependencies." **-->** "You will learn how to use Contexts and Dependency Injection (CDI) in a simple inventory management application to manage scopes and inject dependencies."
=> Not changed since CDI  is spelled out in the section under the title. 
- [x] "The implementation of the application and its services are provided for you" **-->** "The implementation of the inventory application and its services are provided for you under the `start/src` directory. The `system` service can be found under `start/src/main/java/io/openliberty/guides/system` and the `inventory` service can be found under `start/src/main/java/io/openliberty/guides/inventory`. All common files are located under `start/src/main/java/io/openliberty/guides/common`."
=> Fixed
- [x] "If you want to learn how to build a RESTful web service" **-->** "If you want to learn more about RESTful web services and how to build them, follow ..."
=> Fixed
- [x] "You will use CDI to inject dependencies into the application and you will learn how to manage the life cycles of your objects." **-->** remove this sentence, its a repeat of the first sentence in this section.
=> Reworked
- [x] "The system and Inventory services..." **-->** remove this sentence, it would be a repeat of the information above (if you choose to add it).
=> Reworked

**Handling dependencies in the application**
- [x] "You will use scopes and contexts in this application to manage the life cycles of your objects. You will also inject a dependency from one class into another class." **-->** scopes define contexts from what I understand, so its confusing to say "you will use scopes and contexts" because it makes it seem like they are two different things. I would change this sentences to something like "Objects can be bound to well defined-contexts using scopes. CDI provides a variety of scopes for you to work with and while you will not use all of them in this guide, there is one for almost every scenario that you may encounter. Scopes are defined using CDI annotations." Then add a new paragraph: "Dependency injection enables you to inject a bean in its specified context without having to instantiate it yourself. Use dependency injection to inject one bean into another to make use of its functionalities."
=> Fixed

**Managing scopes and contexts**
- [x] Change this section title to "Binding stateful components to lifecycle contexts"
=> "Binding stateful components to lifecycle contexts" as a section title seems bit too descriptive, and it's not consistent with the other section title. No change. 
- [x] I think here is where you can make the changes we talked about; ie. say something like "Take a look at `src/main/java/io/openliberty/guides/inventory/InventoryManager.java`. This bean manages the inventory, adds new entries, removes old ones, etc. It also contains the actual storage for all of the entries, essentially making it our database as well. Therefore, it must be persistent between all the clients. To do this, add the `@ApplicationScoped` annotation on the class. This annotation indicates that this particular bean is to be initialized once per the application scope. By making it application-scoped, the container ensures that the same instance of the bean is used whenever
its injected in the application." Then list the class. You probably also won't need to mention the ConcurrentMap as a result. Repeat for the other classes.
=> Reworked to have user create the class instead.
- [x] you need to say where the utility components can be found. Use what I had before: "Finally, we are giving you two utility components: a `InventoryUtil` class and the `JsonMessages` enum.
These can be found under `src/main/java/io/openliberty/guides/common/inventory/util` and `src/main/java/io/openliberty/guides/common/common` respectively.
=> Fixed.

- The `InventoryUtil` class is responsible for communicating with the `system` service to retrieve JVM
system properties for a particular host that exposes them.
- The `JsonMessages` enum is used to build JSON Java objects for various error cases. Currently its
only used to build an error JSON whenever a particular host does not exist or is not running the `system` service.

Both of these contain detailed Javadocs, so feel free to read them for reference."

**Injecting dependency**
- [x] The title should be "Injecting a dependency"
=> Fixed.
- [x] Don't say "add the @Inject annotation" because the annotation is already there. Just explain what the annotation is without showing it again. Something like "Recall the `InventoryResource` class. The `@Inject` annotation indicates a dependency injection. In this case, you are injecting your `InventoryManager` bean into the `InventoryResource` class. This injects the bean in its specified context (application-scoped) and makes all of its functionalities available without the need of instantiating it yourself. The injected bean can then be invoked directly via the `manager.get(hostname)` and `manager.list()` function calls."
=> Fixed.

Everything else looks good otherwise. The start and finish are consistent, and the guide is fairly easy to follow. The structure should be good, but it would be better if you make the changes we talked about this morning.
=> Thanks a lot for your review and feedback.

**Comment by yeekangc** [comment]
I don't think we need the PNG under resources too.  If it is not needed anymore, we should remove it.

**Comment by evelinec** [comment]
To be fixed in #21.
